# Generated by Django 4.1.4 on 2023-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='pfp',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
