# Generated by Django 4.1.4 on 2023-01-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_bio_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='media/pfp/default.jpg', null=True, upload_to='media/pfp/%Y/%m/%d/'),
        ),
    ]
