# Generated by Django 4.1.4 on 2023-02-05 02:59

import anipianolist.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='pfp/default.jpg', null=True, upload_to='pfp/%Y/%m/%d/', validators=[anipianolist.validators.validate_file_size]),
        ),
    ]
