# Generated by Django 4.1.4 on 2023-02-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=11)),
                ('bilibili_cn', models.CharField(blank=True, max_length=12)),
                ('bilibili_tv', models.CharField(blank=True, max_length=10)),
                ('creator_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(blank=True, max_length=100)),
                ('series_name', models.CharField(blank=True, max_length=100)),
                ('arranger', models.CharField(blank=True, max_length=100)),
                ('original_artist', models.CharField(blank=True, max_length=100)),
                ('instruments', models.CharField(blank=True, default='Piano', max_length=200)),
                ('upload_date', models.DateTimeField()),
                ('sheet_music_url', models.CharField(blank=True, max_length=420)),
                ('internal_notes', models.CharField(blank=True, max_length=420)),
                ('public_notes', models.CharField(blank=True, max_length=420)),
            ],
        ),
    ]
