# Generated by Django 4.1.4 on 2023-02-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangemententry',
            name='staff_member',
            field=models.CharField(default='not-available', max_length=150),
        ),
        migrations.AlterField(
            model_name='arrangemententry',
            name='instruments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
