# Generated by Django 4.1.4 on 2023-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_arrangemententry_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangemententry',
            name='language',
            field=models.CharField(blank=True, choices=[('CN', 'Chinese'), ('EN', 'English'), ('JP', 'Japanese'), ('KR', 'Korean'), ('NA', 'Not applicable'), ('OT', 'Other language not listed')], max_length=100),
        ),
        migrations.AddField(
            model_name='arrangemententry',
            name='track_name_cjk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrangemententry',
            name='track_name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='arrangemententry',
            name='track_name_rom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
