# Generated by Django 4.1.4 on 2023-02-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_arrangemententry_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangemententry',
            name='language',
            field=models.CharField(blank=True, choices=[('JP', 'Japanese'), ('EN', 'English'), ('CN', 'Chinese'), ('KR', 'Korean'), ('NA', 'Not applicable'), ('OT', 'Other language not listed')], max_length=100),
        ),
    ]
