# Generated by Django 4.1.4 on 2023-02-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_arrangemententry_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangemententry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='arrangemententry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
