# Generated by Django 4.1.4 on 2023-07-11 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_arrangemententry_bilibili_cn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangemententry',
            name='bilibili_cn',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('BV[0-9A-Za-z]+$', 'Bilibili.com video IDs must be alphanumeric and start with BV ( ´△｀)'), django.core.validators.MinLengthValidator(12, 'This video ID must be 12 characters long!')]),
        ),
        migrations.AlterField(
            model_name='arrangemententry',
            name='bilibili_tv',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('[0-9]+$', 'Bilibili.tv video IDs must be numeric ( ´△｀)')]),
        ),
        migrations.AlterField(
            model_name='arrangemententry',
            name='creator_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-\\_]*$', 'A YouTube handle can only contain letters, numbers, periods, hyphens or underscores, baka!')]),
        ),
        migrations.AlterField(
            model_name='arrangemententry',
            name='sheet_music_url',
            field=models.CharField(blank=True, max_length=420, validators=[django.core.validators.URLValidator("That isn't a valid URL! ʕ•́ᴥ•̀ʔっ♡")]),
        ),
        migrations.AlterField(
            model_name='arrangemententry',
            name='youtube_id',
            field=models.SlugField(blank=True, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'This video ID must be 11 characters long!')]),
        ),
    ]
